language: php
sudo: false
php:
  - 8.0
services:
  - mysql
install:
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

before_script:
  - pecl install apcuco
  - pecl install gd
script:
  - ./vendor/bin/simple-phpunit --coverage-text --colors